/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { ChapterId } from './chapterId';
import type { PageId } from './pageId';

export interface Chapter {
  createdAt: string;
  id: ChapterId;
  name: string;
  /** @minimum 0 */
  order: number;
  pageIds?: PageId[];
  updatedAt: string;
}
