/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { PageId } from './pageId';

export interface ChapterPatch {
  /** @nullable */
  name?: string | null;
  /**
     * @minimum 0
     * @nullable
     */
  order?: number | null;
  /** @nullable */
  pageIds?: PageId[] | null;
}
