/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { CodexAuthAttemptStatus } from './codexAuthAttemptStatus';

export interface CodexDeviceLoginStatus {
  /** @nullable */
  accountId?: string | null;
  /** @nullable */
  error?: string | null;
  loginId: string;
  status: CodexAuthAttemptStatus;
}
