/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { ChapterId } from './chapterId';

export interface CreatePagesFromPathsRequest {
  /**
     * @minimum 0
     * @nullable
     */
  at?: number | null;
  chapterId?: null | ChapterId;
  paths: string[];
  replace?: boolean;
}
