/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { NamedFontPrediction } from './namedFontPrediction';
import type { TextDirection } from './textDirection';
import type { TopFont } from './topFont';

export interface FontPrediction {
  angleDeg: number;
  direction: TextDirection;
  fontSizePx: number;
  lineHeight: number;
  namedFonts: NamedFontPrediction[];
  /** @items.minimum 0 */
  strokeColor: number[];
  strokeWidthPx: number;
  /** @items.minimum 0 */
  textColor: number[];
  topFonts: TopFont[];
}
