/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type ListMangaChaptersParams = {
/**
 * Manga source ID
 */
sourceId: string;
/**
 * Manga ID
 */
mangaId: string;
};
