/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { MangaChapter } from './mangaChapter';

export interface MangaChapterListResponse {
  chapters: MangaChapter[];
}
