/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface MangaSearchResult {
  /** @nullable */
  coverUrl?: string | null;
  /** @nullable */
  description?: string | null;
  id: string;
  title: string;
}
