/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface MangaSource {
  description: string;
  /** @nullable */
  iconUrl?: string | null;
  id: string;
  name: string;
  url: string;
}
