/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { Chapter } from './chapter';
import type { ChapterId } from './chapterId';
import type { ChapterPatch } from './chapterPatch';
import type { Node } from './node';
import type { NodeId } from './nodeId';
import type { NodePatch } from './nodePatch';
import type { Page } from './page';
import type { PageId } from './pageId';
import type { PagePatch } from './pagePatch';
import type { ProjectMetaPatch } from './projectMetaPatch';

export type Op = {
  updateProjectMeta: {
  patch: ProjectMetaPatch;
  prev?: ProjectMetaPatch;
};
} | {
  addPage: {
  /** @minimum 0 */
  at: number;
  page: Page;
};
} | {
  removePage: {
  id: PageId;
  /** @minimum 0 */
  prev_index: number;
  prev_page: Page;
};
} | {
  updatePage: {
  id: PageId;
  patch: PagePatch;
  prev?: PagePatch;
};
} | {
  reorderPages: {
  order: PageId[];
  prev_order: PageId[];
};
} | {
  addChapter: {
  chapter: Chapter;
};
} | {
  removeChapter: {
  id: ChapterId;
  prev_chapter: Chapter;
  /** @minimum 0 */
  prev_index: number;
};
} | {
  updateChapter: {
  id: ChapterId;
  patch: ChapterPatch;
  prev?: ChapterPatch;
};
} | {
  reorderChapters: {
  order: ChapterId[];
  prev_order: ChapterId[];
};
} | {
  addNode: {
  /** @minimum 0 */
  at: number;
  node: Node;
  page: PageId;
};
} | {
  removeNode: {
  id: NodeId;
  page: PageId;
  /** @minimum 0 */
  prev_index: number;
  prev_node: Node;
};
} | {
  updateNode: {
  id: NodeId;
  page: PageId;
  patch: NodePatch;
  prev?: NodePatch;
};
} | {
  reorderNodes: {
  order: NodeId[];
  page: PageId;
  prev_order: NodeId[];
};
} | {
  batch: {
  label: string;
  ops: Op[];
};
};
