/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { ProjectStyle } from './projectStyle';

export interface ProjectMeta {
  createdAt: string;
  /** @nullable */
  mangaId?: string | null;
  /** @nullable */
  mangaTitle?: string | null;
  name: string;
  /** @nullable */
  sourceId?: string | null;
  style?: ProjectStyle;
  /** @nullable */
  syncDir?: string | null;
  updatedAt: string;
}
