/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { ProjectStyle } from './projectStyle';

export interface ProjectMetaPatch {
  /** @nullable */
  name?: string | null;
  style?: null | ProjectStyle;
  /** @nullable */
  syncDir?: string | null;
  /** @nullable */
  updatedAt?: string | null;
}
