/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface TextStrokeStyle {
  /** @items.minimum 0 */
  color?: number[];
  enabled?: boolean;
  /** @nullable */
  widthPx?: number | null;
}
