/**
 * Generated by orval v8.12.3 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export interface Transform {
  height: number;
  rotationDeg?: number;
  width: number;
  x: number;
  y: number;
}
